# Generated by Django 4.2.3 on 2023-07-21 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=250)),
                ('question_en', models.CharField(max_length=250, null=True)),
                ('question_de', models.CharField(max_length=250, null=True)),
                ('answer', models.TextField()),
                ('answer_en', models.TextField(null=True)),
                ('answer_de', models.TextField(null=True)),
            ],
        ),
    ]
