# Generated by Django 4.2.3 on 2023-07-21 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('new_image', models.ImageField(upload_to='gallery_folder')),
                ('day_publish', models.DateField()),
            ],
        ),
    ]
